# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Like tears in the rain
sign: 成为更好的人
email: 357863248@qq.com
phone: 13056665034
career: iOS程序猿

description: > # this means to ignore newlines until "baseurl:"
          努力这回事，最有意思的地方就在于明明知道它毫无意义，却还是愿意试上一试
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wangkunkun.github.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  WangKunKun


# Build settings
markdown: kramdown
