# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Like tears in the rain
sign: 成为更好的人
qq: 357863248
phone: 13056665034
career: iOS程序猿
email: tomorrow.goodman@gmail.com

description: > # this means to ignore newlines until "baseurl:"
          重要的不说你所处的位置，而是你所朝的方向
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wangkunkun.github.com" # 远程the base hostname & protocol for your site
# url: "http://localhost:4000/" #本地测试
# twitter_username: jekyllrb
github_username:  WangKunKun

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 15 # pagination based on number of posts 分页 每一页多少
paginate_path: "page:num"
gems: [jekyll-paginate, jekyll-gist] #增加这一行
kramdown:
  input: GFM
  syntax_highlighter: rouge

